### ISSUE TITLE
Support sealed traits 

### ISSUE THREAD

**Issue by markus1189** [medeia/medeia#20]

**Comment by froth** [comment]
@markus1189 
when encoding 
`sealed trait Trait 
case class A(s: String)`

should it look like:
`{
"configurableMagicTypeTag" : "A",
"s":"Paprika"
}`

or like:
`{
"A" : { "s": "Salmon"}
}`

First one is also used by circe generics extra

second one does not have a magic tag but leads to a deeper db model by default and in the outer BsonDocument only one entry is allowed.

I tend to the first solution but am unsure.

The other circe codecs use: try codecs until one fits, which I really dislike because ew....

**Comment by froth** [comment]
The first solution also allows to set a mongoindex on configurableMagicTypeTag

**Comment by markus1189** [comment]
I'm in favor of the circe way, e.g. adding the type-tag.  I think it's also an advantage, that other readers of the json that don't care about the type-tag could read the json as-is and just ignore the additional field.

Also, what about nested sum types, with the second approach you would increase the nesting considerably :)
